### PR TITLE
Fix player position performance issue

### LINKED ISSUE #507: Performance issue: Too high CPU usage
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When starting Spotube without playing music, it permanently consumes 80 to 86% CPU.
When playing music, it permanently consumes 80 to 107% CPU.

### Expected Behavior

Much less CPU usage.

### Steps to reproduce

1. open app.
2. optionally, play music.

### Operating System

Linux Debian 11, 64-bit, Mate desktop

### Spotube version

2.7.1

### Installation source

Flathub (Flatpak)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by karniv00l**
Fixes #507

I'm not sure whether this is a correct fix and why it's not present on all platforms, devtools show re-renders every tick:

Screenshot 2023-08-01 at 08 45 10

---

After this fix, when the song is playing, re-render only happens **ever 1s** (update freq of the position slider), when the song is stopped - **zero re-renders**

### CODE REVIEW

File: lib/components/player/player_controls.dart [hunk 1]
```diff
@@ -48,7 +48,6 @@ class PlayerControls extends HookConsumerWidget {
 
     final playing =
         useStream(audioPlayer.playingStream).data ?? audioPlayer.isPlaying;
-    final buffering = useStream(audioPlayer.bufferingStream).data ?? true;
```
Comment (karniv00l) [inline lib/components/player/player_controls.dart:51]: no clue why, but this is also causing re-renders

File: lib/components/player/player_controls.dart [hunk 2]
```diff
@@ -89,215 +88,208 @@ class PlayerControls extends HookConsumerWidget {
       iconSize: compact ? 18 : 24,
     );
 
-    return RepaintBoundary(
```
Comment (karniv00l) [inline lib/components/player/player_controls.dart:92]: Only `RepaintBoundary` and `buffering` removed

File: lib/components/player/player_overlay.dart [hunk 3]
```diff
@@ -62,99 +62,95 @@ class PlayerOverlay extends HookConsumerWidget {
             child: AnimatedOpacity(
               duration: const Duration(milliseconds: 250),
               opacity: canShow ? 1 : 0,
-              child: RepaintBoundary(
```
Comment (karniv00l) [inline lib/components/player/player_overlay.dart:65]: Only `RepaintBoundary` removed

File: lib/hooks/use_progress.dart [hunk 4]
```diff
@@ -9,21 +8,29 @@ import 'package:spotube/services/audio_player/audio_player.dart';
...
-
   final bufferProgress =
       useStream(audioPlayer.bufferedPositionStream).data?.inSeconds ?? 0;
 
+  Duration audioPlayerDuration = Duration.zero;
+  Duration audioPlayerPosition = Duration.zero;
+
   // Duration future is needed for getting the duration of the song
   // as stream can be null when no event occurs (Mostly needed for android)
-  final durationFuture = useFuture(audioPlayer.duration);
```
Comment (karniv00l) [inline lib/hooks/use_progress.dart:19]: both `useFuture`s cause `useProgress` to re-create

File: lib/hooks/use_progress.dart [hunk 5]
```diff
@@ -9,21 +8,29 @@ import 'package:spotube/services/audio_player/audio_player.dart';
   Duration duration,
   double bufferProgress
 }) useProgress(WidgetRef ref) {
-  final playlist = ref.watch(ProxyPlaylistNotifier.provider);
```
Comment (karniv00l) [inline lib/hooks/use_progress.dart:12]: Unused

**Comment by KRTirtho** [comment]
That's awesome work :rocket:. Let me quickly check

**Comment by KRTirtho** [comment]
The CPU usage has dramatically reduced now :rocket: 
Left - Changed (Task Manager 2nd) |||| Right - Old Version (Task Manager 1st)
image

**Comment by KRTirtho** [comment]
This is when all music is paused
image
